### PR TITLE
Fix custom type misdetection

### LINKED ISSUE #4: False positive: trailing comma for functions in if clause
See: https://github.com/voxpupuli/puppet-archive/pull/264

```
  if $file_path !~ Stdlib::Compat::Absolute_path {
    fail("archive::artifactory[${name}]: \$name or \$archive_path must be an absolute path!")
  }
```

results into an error:

```
trailing_comma:WARNING:missing trailing comma after last element
```

### PR DESCRIPTION
**Pull request by seanmil**
Fix issue reported in #4 as well as false positives for function definitions that specify a custom return type.

Fixes #4

### CODE REVIEW

File: spec/puppet-lint/plugins/check_trailing_comma/check_trailing_comma_spec.rb [hunk 1]
```diff
@@ -55,6 +55,17 @@ class { '::apache':
...
         }
+
+        function myfunc (
+          Mymod::Mytype $arg1,
+          String[1] $arg2,
+        ) >> Mymod::Mytype {
+          notice('foo')
+        }
+
+	if $var =~ Sensitive {
```
Comment (ekohl) [inline spec/puppet-lint/plugins/check_trailing_comma/check_trailing_comma_spec.rb]: Can you use spaces here for indenting like the rest of the file?

File: spec/puppet-lint/plugins/check_trailing_comma/check_trailing_comma_spec.rb [hunk 2]
```diff
@@ -55,6 +55,17 @@ class { '::apache':
             '/etc/baz.conf', '/etc/baz.conf.d'
              ],
         }
+
+        function myfunc (
+          Mymod::Mytype $arg1,
+          String[1] $arg2,
+        ) >> Mymod::Mytype {
```
Comment (ekohl) [inline spec/puppet-lint/plugins/check_trailing_comma/check_trailing_comma_spec.rb]: What's this syntax? I haven't seen this before.

File: spec/puppet-lint/plugins/check_trailing_comma/check_trailing_comma_spec.rb (hunk 1 above)
Comment (seanmil) [reply spec/puppet-lint/plugins/check_trailing_comma/check_trailing_comma_spec.rb]: Yes, sorry about that. I wasn't using my normal development environment when I did this patch. Fixed.

File: spec/puppet-lint/plugins/check_trailing_comma/check_trailing_comma_spec.rb (hunk 2 above)
Comment (seanmil) [reply spec/puppet-lint/plugins/check_trailing_comma/check_trailing_comma_spec.rb]: Which syntax? The custom data types or typed function return values? They are both new with Puppet 4.x:
https://puppet.com/docs/puppet/5.5/lang_type_aliases.html
and
https://puppet.com/docs/puppet/5.5/lang_write_functions_in_puppet.html#return-types

**Comment by ekohl** [comment]
Thanks!
